### ISSUE TITLE
Detect log file and avoid unnecessary work

### ISSUE THREAD

**Issue by JohnsonClayton** [JohnsonClayton/Mustang-Detection-System#19]
Create a script to automatically detect if the program has been run (by the presence of the `log.txt` file) and pull the JSON data from this file to keep track of which files will NOT be reclassified.

**Comment by JohnsonClayton** [comment]
also make it so the log file is automatically updated while the program is running i.e. we can terminate the program halfway through execution and still recover progress

**Comment by sjmarshall2000** [comment]
part 1 of this issue description complete

**Comment by JohnsonClayton** [comment]
I've reorganized the outputting format to occur as execution is occurring instead of all the logging happening at the end: 613817c44e0b1ef502aa53d00b1dedda902844fe

**Comment by JohnsonClayton** [comment]
Updated with ability to recover from failed or cancelled sessions with the log file: e628c15e5803f3ff105727a7b40f185d106493de

**Comment by JohnsonClayton** [comment]
958e3d709d0239adad2d30b4bae2f7ab6e1c66df
